# Application Info
spring.application.name=nebulastock


# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/nebulastock
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway (DB Migration)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Server
server.port=8080